### ISSUE TITLE
Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by axi92** [erdtman/aes-ccm#11]
I got this error:

```
internal/modules/cjs/loader.js:1025
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/plehner/Workspace/git/ng-hex2img/node_modules/aes-ccm/lib/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

With the example code. Did I miss something? aes_ccm.node is in the ..../build/Release folder.

**Comment by axi92** [comment]
Got it fixed with this: https://github.com/alexander-akhmetov/python-telegram/issues/3#issuecomment-438061449
